name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and test code
        run: |
          npm run build
          npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

  check-suite:
    runs-on: ubuntu-latest
    needs: [build, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check if all checks have passed
        uses: peter-evans/wait-for-checks@v1
        with:
          checks: build, lint
          wait-for-completion: true
          status: success
